# Generated by Django 4.2.10 on 2024-03-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
                ('price_usd', models.CharField(max_length=20)),
                ('percent_change_24h', models.FloatField()),
                ('percent_change_1h', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('market_cap_usd', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CoinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
            ],
        ),
    ]
