# Generated by Django 4.2.10 on 2024-03-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='percent_change_1h',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_24h',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='coin',
            name='percent_change_7d',
            field=models.CharField(max_length=5),
        ),
    ]
